create table "user"
(
    id_user           integer generated always as identity (minvalue 0 maxvalue 65500)
        constraint id_user_pk
            primary key,
    username          varchar(32)               not null
        constraint username_pk
            unique,
    password          varchar(128)              not null,
    bio               varchar(256),
    date_created      date default CURRENT_DATE not null,
    avatar_path       varchar(256),
    deactivation_date date
);

alter table "user"
    owner to test;

create table user_review
(
    id_review    integer generated always as identity (minvalue 0)
        constraint id_review_pk
            primary key,
    type         boolean                   not null,
    tmdb_id      integer                   not null,
    rating       integer                   not null,
    comment      char(1024),
    date_created date default CURRENT_DATE not null,
    user_id      integer                   not null
        constraint user_review_user_id_user_fk
            references "user"
);

alter table user_review
    owner to test;

create table user_favourite
(
    id_favorite  integer generated always as identity (minvalue 0),
    type         boolean default true         not null,
    tmdb_id      integer                      not null,
    title        varchar(256),
    date_added   date    default CURRENT_DATE not null,
    release_year integer,
    poster_path  varchar(256),
    user_id      integer                      not null
        constraint user_favourite_user_id_user_fk
            references "user"
);

alter table user_favourite
    owner to test;

create table "group"
(
    id_group     integer generated always as identity (minvalue 0)
        constraint group_pk
            primary key,
    name         varchar(32)                  not null
        constraint group_name_pk
            unique,
    date_created date    default CURRENT_DATE not null,
    description  varchar(256),
    icon_path    varchar(256),
    active       boolean default true         not null,
    owner_id     integer                      not null
        constraint group_user_id_user_fk
            references "user"
            on delete cascade
);

alter table "group"
    owner to test;

create table user_group
(
    id_user_group integer generated always as identity (minvalue 0)
        constraint user_group_pk
            primary key,
    active        boolean default false not null,
    user_id       integer               not null
        constraint user_group_user_id_user_fk
            references "user"
            on delete cascade,
    group_id      integer               not null
        constraint user_group_group_id_group_fk
            references "group"
            on delete cascade
);

alter table user_group
    owner to test;

create table group_item
(
    id_group_item serial
        primary key,
    type          boolean      not null,
    tmdb_id       integer      not null,
    title         varchar(256) not null,
    poster_path   varchar(256),
    release_year  integer,
    date_added    timestamp default CURRENT_TIMESTAMP,
    group_id      integer      not null
        references "group"
            on delete cascade
);

alter table group_item
    owner to test;

create table group_join_request
(
    user_id       integer not null,
    group_id      integer
        constraint group_join_request_group_groupid_fk
            references "group"
            on delete cascade,
    status        varchar(32),
    request_date  date default CURRENT_DATE,
    request_id    integer generated by default as identity,
    response_date date
);

alter table group_join_request
    owner to test;


